### ISSUE TITLE
Fake Scirpt

### ISSUE THREAD

**Issue by ProTechEx** [hax0rtahm1d/Decrypt#1]
Doesn't do anything. Output file is empty. Fake Scirpt!

**Comment by htr-tech** [comment]
lol... if your script is obfuscated with [bash-obfuscate](https://www.npmjs.com/package/bash-obfuscate)

just replace the "eval"  with "echo" & run.... The script does the same....

i have made it opensource ... so checkout [c5b1ce9](https://github.com/hax0rtahm1d/Decrypt/commit/c5b1ce914f7d4211136e707f6bcf4535c4f24308)

#peace 🤟
